### ISSUE TITLE
Tansmit Connect Command (Favourite)

### ISSUE THREAD

**Issue by biskander** [fabiospampinato/vscode-transmit#1]
Would be nice if you could access a different _transmit.favorite_ than the 'default' via the connect command.

**Comment by fabiospampinato** [comment]
What is your use case exactly?

This extension was developed with a single server in mind, but maybe it should be generalized a bit.

**Comment by fabiospampinato** [comment]
Implemented in v2, servers are now defined under the `settings.servers` setting.
