### ISSUE TITLE
Connect to server, not just site

### ISSUE THREAD

**Issue by iamandrewpeters** [fabiospampinato/vscode-transmit#3]
Hey there! I noticed in the overview there is a line for  "domain": "", // Domain to connect to (e.g. example.com)

My problem is, I don't just want to connect to one site. I want to connect to a server and see all the sites on that server, but it doesn't seem I can leave that line blank or delete it and just connect to the server itself?

**Comment by fabiospampinato** [comment]
You should be able to put the IP address of the server in there. If you can't I'll reopen this since it would be a bug.

**Comment by iamandrewpeters** [comment]
As the domain name? I’ll give that a go.

**Comment by fabiospampinato** [comment]
Yeah
